<?php

namespace Database\Seeders;

class AutoCAD21DaysSeeder extends Cad21DaysSeeder
{
    protected function config(): array
    {
        return [
            'slug' => '21-ngay-chinh-phuc-tool-autocad-bang-ai-agent',
            'title' => '21 Ngày Chinh Phục Tool AutoCAD bằng AI Agent',
            'boss_name' => 'DSCons AutoCAD Mentor',
            'app_name' => 'AutoCAD',
            'version_line' => 'AutoCAD 2019–2026; profile build theo version đang dùng',
            'description' => 'Lộ trình thực chiến giúp kỹ sư BIM/MEP dùng AI Agent để xây plugin AutoCAD .NET, tự động hóa bản vẽ, kiểm thử an toàn và đóng gói bộ cài có thể chạy lại.',
        ];
    }

    protected function days(): array
    {
        return [
            $this->guidedDay(1, 'live', 'common', 'Khởi động workspace AutoCAD và chạy Starter', 'Khai hoả', 90,
                'Kickoff giúp học viên hiểu đầu ra cuối khóa, mở đúng AutoCAD Kit, kiểm tra môi trường và chạy lệnh Starter trên DWG bản sao.',
                ['Xác định tool cuối khóa.', 'Chạy preflight và mở workspace.', 'AI đọc được cấu trúc thư mục.'],
                ['AutoCAD không phải LT.', 'Có DWG không chứa dữ liệu mật.'],
                ['Chạy preflight ở chế độ kiểm tra.', 'Mở DWG bản sao, build Starter và chạy DSC_HELLO bằng NETLOAD.', 'Ghi version AutoCAD và đầu ra cuối khóa.'],
                ['Ảnh workspace/preflight.', 'Video 30–60 giây chạy DSC_HELLO.', 'Ba câu reflection.'],
                ['NETLOAD trên DWG gốc.', 'Tự cài dependency khi chưa xác nhận.', 'Chỉ nộp ảnh thư mục.'],
                'Môi trường mở được kit và Starter chạy thật trong AutoCAD',
                ['DWG bản sao nằm ở đâu?', 'DLL nào được load?', 'Preflight thiếu dependency thì làm gì?']),
            $this->guidedDay(2, 'video', 'common', 'Lập kế hoạch trước khi viết plugin', 'AI Agent', 35,
                'Học viên dùng AI Agent để khảo sát kit, hỏi ngược bài toán và tạo kế hoạch thay đổi trước khi AI viết C#.',
                ['Phân biệt chatbot và AI Agent.', 'Có kế hoạch file/build.', 'Biết điểm cần xác nhận.'],
                ['Đã đọc START_HERE và workflow.', 'Có tên tool tạm thời.'],
                ['Yêu cầu AI đọc AGENTS.md, CLAUDE.md và TOOL_BRIEF.md.', 'Lưu kế hoạch thành AI_WORKFLOW.md.', 'Đánh dấu giả định cần kiểm chứng.'],
                ['AI_WORKFLOW.md.', 'Ảnh file dự kiến sửa.', 'Một quyết định học viên tự xác nhận.'],
                ['Cho AI code ngay.', 'Không ghi version.', 'Không có rollback/test.'],
                'Có kế hoạch được review trước khi tạo code',
                ['AI được sửa file nào?', 'Lệnh nào cần học viên xác nhận?', 'Kế hoạch đủ khi nào?']),
            $this->guidedDay(3, 'video', 'common', 'Kiểm tra version và build profile AutoCAD', 'Preflight', 45,
                'AI giải thích profile net47/net48/net8.0-windows theo version AutoCAD và giúp học viên ghi compatibility trung thực.',
                ['Xác định đúng version/edition.', 'Chọn build profile đúng.', 'Biết lỗi môi trường critical.'],
                ['Có kết quả ngày 1.', 'Đã mở SETUP.md và profiles.'],
                ['Chạy scripts/preflight.ps1.', 'Ghi .NET, Developer Pack, Git và reference.', 'Lưu environment-report.json.', 'Không tự đổi TRUSTEDPATHS/SECURELOAD.'],
                ['Báo cáo PASS/FAIL.', 'Bảng version/target.', 'Danh sách lỗi đã xử lý.'],
                ['Build 2024 rồi tuyên bố mọi version.', 'Bỏ qua thiếu Developer Pack.', 'Tự đổi cấu hình bảo mật.'],
                'Biết profile build và giới hạn version của máy',
                ['Profile nào dành cho version?', 'Thiếu dependency nào?', 'Build pass khác runtime pass ra sao?']),
            $this->guidedDay(4, 'video', 'common', 'Tạo command AutoCAD đầu tiên', 'CommandMethod', 50,
                'Từ Starter, AI tạo command .NET có tên rõ ràng; học viên build DLL, NETLOAD trên bản sao và kiểm tra log.',
                ['Hiểu CommandMethod.', 'DLL load được.', 'Command đọc không sửa DWG.'],
                ['Preflight không còn lỗi critical.', 'Có DWG bản sao.'],
                ['Đọc HelloCommand.cs và csproj.', 'Chốt tên command.', 'Build Release, NETLOAD, chạy command và chụp kết quả.', 'Yêu cầu AI giải thích entry point.'],
                ['Log build.', 'Video command chạy thật.', 'Ba câu reflection.'],
                ['Load DLL cũ.', 'Đăng ký command sai.', 'Chạy trên DWG gốc.'],
                'Có command cá nhân hóa load được trong AutoCAD',
                ['Command đăng ký ở đâu?', 'DLL đang load là DLL nào?', 'Rollback thế nào?']),
            $this->guidedDay(5, 'video', 'common', 'Đọc Document, Database, Layer và BlockTable', 'Database API', 60,
                'Học viên khảo sát cấu trúc bản vẽ bằng API đọc dữ liệu, chưa tạo hoặc sửa entity.',
                ['Đọc thông tin bản vẽ.', 'Phân biệt Document/Database/table.', 'Có output đối chiếu được.'],
                ['Command ngày 4 chạy.', 'DWG có Layer và Block.'],
                ['Tạo read-only inspector.', 'Đọc LayerTable, BlockTable và số lượng.', 'Đối chiếu ba thông tin với UI AutoCAD.', 'Ghi API chưa runtime test.'],
                ['Ảnh inspector.', 'Bảng Layer/Block.', 'Reflection về dữ liệu.'],
                ['Mở transaction ghi.', 'Đếm sai BlockReference.', 'Hard-code Layer không tồn tại.'],
                'Có báo cáo đọc được cấu trúc bản vẽ',
                ['Database khác Document thế nào?', 'LayerTable chứa gì?', 'Đối chiếu ở đâu?']),
            $this->guidedDay(6, 'video', 'common', 'Lọc Entity và đọc thuộc tính bằng Transaction', 'Transaction', 60,
                'AI xây truy vấn đọc Entity, Layer, Block, Text và Dimension; học viên hiểu điều kiện lọc và transaction chỉ đọc.',
                ['Lọc được nhóm entity.', 'Đọc thuộc tính cần thiết.', 'Xử lý model không có kết quả.'],
                ['Hoàn thành ngày 5.', 'Có ít nhất 5 entity để kiểm tra.'],
                ['Chọn entity type/Layer cần lọc.', 'Dùng transaction read-only, không hard-code ObjectId.', 'Test điều kiện bình thường và rỗng.', 'Đối chiếu 5–10 entity với Properties.'],
                ['Câu truy vấn nâng cao.', 'Bảng entity/thuộc tính.', 'Ảnh Properties.'],
                ['Sai transaction mode.', 'Lấy nhầm entity.', 'Empty result làm crash.'],
                'Truy vấn có điều kiện và giải thích được kết quả',
                ['Điều kiện lọc ở đâu?', 'Entity bị loại thế nào?', 'Empty result báo gì?']),
            $this->guidedDay(7, 'video', 'common', 'Chọn capstone và hoàn thiện Tool Brief', 'Chọn bài toán', 60,
                'Học viên thu nhỏ một workflow AutoCAD lặp lại thành tool có output đo được.',
                ['Chọn một nhánh.', 'Nêu input/output/giới hạn.', 'Có success metric.'],
                ['Hoàn thành ngày 1–6.', 'Có workflow không chứa dữ liệu mật.'],
                ['Chọn Dựng hình, Layer/Block/Property, Annotation/QA hoặc Xuất dữ liệu.', 'Điền TOOL_BRIEF.md.', 'Yêu cầu AI phỏng vấn ngược.', 'Viết acceptance test và ba lỗi.'],
                ['Tool Brief.', 'Sơ đồ input → output.', 'Success metric và test case.'],
                ['Chọn tool làm mọi thứ.', 'Không có output đo được.', 'Đưa dữ liệu mật vào brief.'],
                'Một Tool Brief đủ nhỏ để hoàn thành trong hai tuần',
                ['Tiết kiệm thao tác nào?', 'Output đo bằng gì?', 'Bỏ tính năng nào khi thiếu thời gian?']),
            $this->guidedDay(8, 'live', 'common', 'Review và chốt capstone với mentor', 'Livestream chốt đề tài', 120,
                'Mentor kiểm tra phạm vi, API và viết lại prompt triển khai riêng cho từng học viên.',
                ['Trình bày brief 3 phút.', 'Có go/no-go.', 'Có acceptance criteria.'],
                ['Đã nộp Tool Brief.', 'Có bản sao DWG.'],
                ['Demo vấn đề → input → thao tác → output → giới hạn.', 'Ghi feedback mentor.', 'Cập nhật brief sau live.', 'Chờ xác nhận trước scaffold.'],
                ['Video/bản ghi.', 'Brief sau review.', 'Biên bản mentor.'],
                ['Không có output đo được.', 'Code trước khi duyệt.', 'Đổi đề tài không cập nhật brief.'],
                'Đề tài được duyệt và sẵn sàng xây MVP',
                ['Tính năng cốt lõi?', 'Demo thành công?', 'Test trên bản sao nào?']),
            $this->guidedDay(9, 'video', 'common', 'Dựng scaffold plugin, Ribbon và About Me', 'Plugin scaffold', 60,
                'AI tạo cấu trúc plugin cá nhân hóa gồm command launcher, Ribbon và About Me.',
                ['Plugin load ổn.', 'Ribbon có tên tool.', 'Biết dependency/cài lại.'],
                ['Tool Brief đã duyệt.', 'Build profile rõ.'],
                ['Đọc starter trước khi tạo file.', 'Liệt kê file thay đổi.', 'Build Release, cài trên bản sao và mở AutoCAD.', 'Bấm Ribbon/About Me.'],
                ['Ảnh Ribbon/About Me.', 'Build log.', 'Mô tả cài lại.'],
                ['Sai target.', 'Thiếu dependency.', 'Button không gọi command.'],
                'Plugin có launcher và nhận diện cá nhân',
                ['Manifest ở đâu?', 'Button gọi command nào?', 'Rollback artifact nào?']),
            $this->guidedDay(10, 'video', 'common', 'Chọn đối tượng bằng SelectionSet', 'Selection', 60,
                'Học viên xây cầu nối chọn đối tượng, lọc theo loại/Layer và truyền selection vào service nghiệp vụ.',
                ['Chọn được nhiều entity.', 'Validation khi chọn sai/rỗng.', 'Service tách khỏi UI.'],
                ['Plugin ngày 9 load.', 'Có entity capstone cần chọn.'],
                ['Dùng PromptSelection/SelectionSet.', 'Test đúng, rỗng và sai loại.', 'Hiển thị số lượng trước Apply.', 'Không ghi model khi chỉ chọn.'],
                ['Video selection.', 'Ảnh validation.', 'Reflection về selection bridge.'],
                ['Không lọc type.', 'Empty selection crash.', 'Service gọi Editor.Get trực tiếp.'],
                'Tool nhận đúng input và báo lỗi rõ',
                ['Selection truyền qua DTO nào?', 'Sai loại báo gì?', 'Transaction bắt đầu khi nào?']),
            $this->guidedDay(11, 'video', 'capstone', 'Thực hiện logic capstone bằng Transaction an toàn', 'Xây chức năng', 75,
                'AI triển khai chức năng đầu tiên của capstone; học viên kiểm tra backup, transaction và log trước/sau.',
                ['Chức năng chạy trên bản sao.', 'Có log thành công/thất bại.', 'Không hỏng DWG gốc.'],
                ['Ngày 8 chốt đề tài.', 'Ngày 10 selection chạy.'],
                ['Sao lưu và mở bản sao.', 'Dán prompt với input/output cụ thể.', 'Yêu cầu Transaction và xử lý read-only/missing property.', 'Chạy 3–5 entity trước.', 'Đối chiếu trước/sau.'],
                ['Video/ảnh trước sau.', 'Log Transaction.', 'Danh sách lỗi.'],
                ['Sửa bản gốc.', 'Không rollback.', 'Ép kiểu property sai.'],
                'Chức năng chính có backup, transaction và log',
                ['Transaction bắt đầu/kết thúc đâu?', 'Một entity lỗi xử lý thế nào?', 'Output đối chiếu đâu?']),
            $this->guidedDay(12, 'video', 'capstone', 'Hoàn thiện logic theo nhánh AutoCAD', 'Capstone MVP', 90,
                'Hoàn thiện dựng hình, layer/block/property, annotation/QA hoặc xuất dữ liệu và xử lý input không hoàn hảo.',
                ['Chạy end-to-end.', 'Thông báo rõ.', 'Xử lý ít nhất ba edge case.'],
                ['Logic ngày 11 chạy.', 'Có acceptance test.'],
                ['Viết happy path, empty, sai entity và lỗi ghi.', 'Yêu cầu guard clause và summary.', 'Chạy từng case và lưu output/log.', 'Cập nhật giới hạn thật vào Tool Brief.'],
                ['Video end-to-end.', 'Bảng test case.', 'Ảnh thông báo lỗi.'],
                ['Báo thành công khi empty.', 'Invalid input làm crash.', 'Catch exception mất nguyên nhân.'],
                'MVP xử lý happy path và báo lỗi hành động được',
                ['Input nào bị từ chối?', 'Một entity lỗi có dừng batch?', 'Thông báo hướng dẫn gì?']),
            $this->guidedDay(13, 'video', 'common', 'Thêm Preview, Apply và Cancel', 'An toàn thao tác', 60,
                'Tool ghi/sửa nhiều đối tượng phải cho người dùng xem trước, xác nhận Apply và hủy mà không sửa DWG.',
                ['Preview không ghi.', 'Apply có confirmation.', 'Cancel/Esc không commit.'],
                ['MVP có thao tác ghi.', 'Có entity mẫu.'],
                ['Tách Preview khỏi Apply.', 'Hiển thị thay đổi dự kiến.', 'Test Apply, Cancel, Close, Esc và exception.', 'So sánh bản vẽ trước/sau.'],
                ['Video Preview → Apply.', 'Ảnh Cancel.', 'Checklist transaction safety.'],
                ['Preview đã ghi model.', 'Không xác nhận batch.', 'Cancel vẫn commit.'],
                'Người dùng kiểm soát được thao tác ghi hàng loạt',
                ['Preview đọc từ đâu?', 'Cancel có commit không?', 'Batch lớn cảnh báo thế nào?']),
            $this->guidedDay(14, 'video', 'common', 'Thiết kế WPF form-first có validation', 'WPF UI', 75,
                'AI tạo WPF theo màu DSCons, có input, loading, empty, success và error state.',
                ['WPF mở/đóng ổn.', 'Nút gọi service thật.', 'Validation tránh input sai.'],
                ['Logic ngày 13 chạy.', 'Đã xem wpf-autocad-ui.'],
                ['Giữ logic hiện có, chỉ thay UI cần thiết.', 'Build và mở từ Ribbon.', 'Test loading/success/error/empty/close.', 'Kiểm tra không che AutoCAD.'],
                ['Ảnh WPF.', 'Checklist 5 state.', 'Video mở/đóng/chạy.'],
                ['UI có nút giả.', 'Không loading.', 'Service gọi trực tiếp UI.'],
                'Giao diện cho kỹ sư biết tool đang làm gì',
                ['Nút gọi method nào?', 'Validation trước transaction chưa?', 'Error hướng dẫn gì?']),
            $this->guidedDay(15, 'live', 'common', 'Review MVP AutoCAD với mentor', 'Livestream review MVP', 120,
                'Mentor kiểm tra Ribbon, selection, command, WPF và transaction trước packaging.',
                ['Demo MVP 3 phút.', 'Có lỗi critical/important.', 'Có go/no-go.'],
                ['Ngày 14 có UI và bug log.', 'Có build Release.'],
                ['Demo mở AutoCAD → Ribbon → input → Preview → Apply → output → error.', 'Ghi feedback.', 'Cập nhật Tool Brief/bug-log.', 'Chỉ sửa lỗi quan trọng trước ngày 16.'],
                ['Video demo.', 'Biên bản review.', 'MVP chạy thật.'],
                ['Demo ảnh cũ.', 'Không có input lỗi.', 'Đóng gói khi command chưa chạy.'],
                'MVP chạy thật và có quyết định packaging rõ',
                ['Tính năng chính đủ chưa?', 'Critical bug nào còn?', 'Cài lại được không?']),
            $this->guidedDay(16, 'video', 'common', 'Hoàn thiện Ribbon và trải nghiệm người dùng', 'UX hoàn thiện', 60,
                'Làm rõ tên nút, tooltip, màu DSCons, trạng thái disabled và thông báo.',
                ['Ribbon dễ hiểu.', 'UI có state/tooltip.', 'Không mở rộng ngoài brief.'],
                ['MVP qua review.', 'Có danh sách feedback.'],
                ['Chọn tối đa ba cải tiến.', 'Cập nhật UI và manual.', 'Build regression chức năng chính.', 'Kiểm tra keyboard/close và label.'],
                ['Ảnh before/after.', 'Video regression.', 'Danh sách feedback.'],
                ['Chỉ đổi màu quên lỗi.', 'Label che nút.', 'UI gọi logic ngoài brief.'],
                'Tool đủ rõ để người khác dùng không cần hỏi lại',
                ['Cải tiến giải quyết feedback nào?', 'Có regression không?', 'Manual đã cập nhật chưa?']),
            $this->guidedDay(17, 'video', 'common', 'Debug, log và DocumentLock an toàn', 'Debug & safety', 60,
                'Học viên sửa lỗi có chủ ý, phân biệt build/API/runtime và kiểm tra lock khi chạy modeless hoặc nhiều document.',
                ['Nêu nguyên nhân lỗi.', 'Biết log tối thiểu.', 'Không mất dữ liệu khi exception.'],
                ['Có MVP và bug log.', 'Có branch/copy test.'],
                ['Tạo lỗi an toàn trên bản sao.', 'Gửi exception/stack trace liên quan cho AI.', 'Yêu cầu giải thích trước sửa.', 'Build lại và regression.', 'Kiểm tra log không chứa dữ liệu mật.'],
                ['Video before/after.', 'Log rút gọn.', 'Ba câu nguyên nhân–sửa–test.'],
                ['Gửi toàn bộ log có secret.', 'Sửa file không liên quan.', 'Chưa test AutoCAD đã kết luận fix.'],
                'Một lỗi có nguyên nhân, bản sửa và regression evidence',
                ['Lỗi môi trường hay code?', 'Log tối thiểu?', 'Test không hồi quy?']),
            $this->guidedDay(18, 'video', 'common', 'Build đa phiên bản AutoCAD', 'Multi-version build', 75,
                'AI tạo build profile AutoCAD 2019–2026; học viên ghi rõ artifact nào đã runtime test.',
                ['Build đúng profile.', 'Không overclaim runtime.', 'Artifact tách theo version.'],
                ['MVP ổn định.', 'Có version mục tiêu.'],
                ['Đọc profiles và da-phien-ban workflow.', 'Build profile mục tiêu và tham chiếu.', 'Đối chiếu dependency.', 'Ghi runtime-tested/build-only vào VERSION_SUPPORT.md.'],
                ['Build log.', 'Support matrix.', 'Ảnh artifact và giới hạn.'],
                ['Dùng DLL 2024 cho mọi version.', 'Trộn dependency.', 'Gọi support chỉ vì build pass.'],
                'Có artifact đúng version và compatibility claim trung thực',
                ['Version nào runtime test?', 'Framework nào?', 'Artifact nào đóng gói?']),
            $this->guidedDay(19, 'video', 'common', 'Đóng gói bundle và kiểm tra rollback', 'Packaging', 75,
                'Gom DLL, PackageContents.xml, dependency, icon, README và rollback thành bộ cài tái sử dụng.',
                ['Có bundle sạch.', 'Cài lại được.', 'Rollback đúng phạm vi.'],
                ['Ngày 15 go.', 'Ngày 18 có build profile.'],
                ['Lập danh sách artifact.', 'Build Release và tạo dist.', 'Tạo bundle theo dong-goi-acad workflow.', 'Cài trên workspace sạch sau xác nhận.', 'Test uninstall/rollback và ghi hash.'],
                ['ZIP trong dist.', 'Video cài/gỡ.', 'Danh sách file/dependency/version.'],
                ['Thiếu dependency.', 'Manifest sai.', 'Rollback xóa file ngoài kit.'],
                'Người khác có thể cài và gỡ tool từ bộ cài',
                ['dist chứa gì?', 'Cài lại từ đâu?', 'Rollback xác định file thế nào?']),
            $this->guidedDay(20, 'video', 'common', 'UAT trên DWG bản sao', 'UAT', 90,
                'Kiểm thử dữ liệu bình thường, thiếu dữ liệu và input sai; output phải đối chiếu được.',
                ['Có test pass/fail.', 'Không sửa DWG gốc.', 'Error message có hành động.'],
                ['Có bộ cài.', 'Có DWG test không mật.'],
                ['Viết bảng UAT trước.', 'Cài từ dist.', 'Chạy happy, missing và invalid input.', 'Lưu output/log/video từng case.', 'Sửa critical rồi regression toàn bộ.'],
                ['Video A–Z 2–3 phút.', 'Bảng test.', 'Regression result.'],
                ['Chỉ test happy path.', 'Dùng ảnh cũ.', 'Không ghi version/model.'],
                'Tool chạy ổn ở ba tình huống và có giới hạn rõ',
                ['Case bắt buộc pass?', 'Input sai báo sao?', 'Có tái hiện lỗi không?']),
            $this->guidedDay(21, 'live', 'common', 'Showcase tool AutoCAD và bàn giao sản phẩm', 'Grand Finale', 120,
                'Trình bày bài toán, quy trình dùng AI, demo tool thật, bộ cài, manual và giới hạn.',
                ['Demo tool thật.', 'Có dist/manual/Tool Brief cuối.', 'Nêu giới hạn và hướng phát triển.'],
                ['UAT ngày 20 đạt.', 'Có video dự phòng nếu vắng live.'],
                ['Trình bày 3 phút bài toán, 3 phút demo, 2 phút Q&A, 1 phút feedback.', 'Mở AutoCAD sạch, cài từ dist và chạy input/output.', 'Demo một lỗi.', 'Nộp Tool Brief, manual, video và support matrix.'],
                ['Video/showcase trực tiếp.', 'Dist và manual.', 'Bài tổng kết before/after.'],
                ['Demo bằng ảnh.', 'Bộ cài không cài lại.', 'Không nêu giới hạn/dùng dữ liệu mật.'],
                'Một tool AutoCAD có thể demo, cài lại, hướng dẫn và đánh giá giới hạn',
                ['Bài toán ban đầu?', 'Kết quả đo bằng gì?', 'Bước tiếp theo?']),
        ];
    }
}
