<?php

namespace Database\Seeders;

class Navisworks21DaysSeeder extends Cad21DaysSeeder
{
    protected function config(): array
    {
        return [
            'slug' => '21-ngay-chinh-phuc-tool-navisworks-bang-ai-agent',
            'title' => '21 Ngày Chinh Phục Tool Navisworks bằng AI Agent',
            'boss_name' => 'DSCons Navisworks Mentor',
            'app_name' => 'Navisworks',
            'version_line' => 'Navisworks Manage/Simulate 2020–2026; Manage 2024 là runtime-certified reference',
            'description' => 'Lộ trình thực chiến giúp kỹ sư BIM/MEP dùng AI Agent để đọc model Navisworks, xây Search Set/DockPane, kiểm tra coordination và xuất báo cáo có thể đối chiếu.',
        ];
    }

    protected function days(): array
    {
        return [
            $this->guidedDay(1, 'live', 'common', 'Khởi động workspace Navisworks và chạy Starter', 'Khai hoả', 90,
                'Kickoff giúp học viên xác định đầu ra, mở đúng Navisworks Kit, kiểm tra edition/version và chạy Starter trên model mẫu.',
                ['Xác định tool cuối khóa.', 'Chạy preflight và build Starter.', 'Hiểu Manage/Simulate và dữ liệu test.'],
                ['Có Navisworks hợp lệ.', 'Có model mẫu không chứa dữ liệu mật.'],
                ['Chạy preflight ở chế độ kiểm tra.', 'Mở model mẫu, build Starter và chạy Hello plugin.', 'Ghi edition/version và đầu ra cuối khóa.', 'Không chạy Clash nếu đang dùng Simulate.'],
                ['Ảnh workspace/preflight.', 'Video 30–60 giây chạy Starter.', 'Ba câu reflection.'],
                ['Dùng model dự án mật.', 'Chạy Clash trên Simulate.', 'Nộp ảnh source thay output.'],
                'Môi trường mở được kit và Starter chạy thật trên model mẫu',
                ['Edition nào?', 'Model mẫu ở đâu?', 'Output đối chiếu thế nào?']),
            $this->guidedDay(2, 'video', 'common', 'Đọc capability matrix trước khi xây tool', 'AI Agent', 40,
                'Học viên yêu cầu AI kiểm tra capability, runtime evidence và giới hạn trước khi tạo nút.',
                ['Phân biệt capability đã chứng minh/chờ test.', 'Có kế hoạch API/file.', 'Không tạo nút giả.'],
                ['Đã đọc START_HERE, KIT_WORKFLOW và CAPABILITY_MATRIX.', 'Có bài toán coordination sơ bộ.'],
                ['Yêu cầu AI tạo capability gate và API spike checklist.', 'Lưu AI_WORKFLOW.md.', 'Đánh dấu feature cần Manage 2024.', 'Chờ xác nhận trước thao tác ghi model/report.'],
                ['AI_WORKFLOW.md.', 'Bảng confirmed/waiting.', 'Một quyết định học viên tự chịu trách nhiệm.'],
                ['Dùng TimeLiner chưa có data.', 'Tuyên bố mọi version certified.', 'Không tạo nút giả cho capability chưa có evidence.'],
                'Có kế hoạch dựa trên capability thật của kit',
                ['Capability chưa publish?', 'Spike cần model gì?', 'Feature nào bỏ khỏi MVP?']),
            $this->guidedDay(3, 'video', 'common', 'Kiểm tra version, edition và build profile', 'Preflight', 45,
                'AI giải thích profile 2020–2026 và cách ghi runtime status; build pass không đồng nghĩa chạy thật.',
                ['Xác định Manage/Simulate.', 'Ghi đúng profile/dependency.', 'Có support matrix.'],
                ['Có kết quả ngày 1.', 'Đã xem SETUP.md và navisworks-versions.json.'],
                ['Chạy scripts/preflight.ps1.', 'Ghi version, edition, .NET, references và kit state.', 'Lưu environment-report.json.', 'Ghi Manage 2024 là reference certified.'],
                ['Báo cáo PASS/FAIL.', 'Bảng version/edition.', 'Support matrix.'],
                ['Dùng Simulate cho Clash.', 'Gọi support chỉ vì build pass.', 'Tự sửa cấu hình hệ thống.'],
                'Biết chính xác môi trường và mức độ hỗ trợ',
                ['Manage khác Simulate ở đâu?', 'Version certified?', 'Lỗi nào chặn build?']),
            $this->guidedDay(4, 'video', 'common', 'Tạo plugin Starter, Ribbon và Hello command', 'Plugin scaffold', 60,
                'AI tạo plugin Navisworks có Ribbon/Hello; học viên build và kiểm tra cài đặt có rollback.',
                ['Plugin load.', 'Ribbon hiển thị DSCons.', 'Có rollback artifact.'],
                ['Preflight không còn critical error.', 'Có model test.'],
                ['Đọc starter/csproj.', 'Liệt kê file/dependency.', 'Build và cài sau xác nhận.', 'Mở Navisworks, chạy Hello/About Me.', 'Ghi đường dẫn rollback.'],
                ['Ảnh Ribbon/About Me.', 'Build log.', 'Mô tả cài/gỡ.'],
                ['Cài khi app mở.', 'Thiếu DLL.', 'Load plugin cũ.'],
                'Plugin có entry point rõ và load được',
                ['Plugin nào load?', 'Ribbon gọi gì?', 'Rollback ngoài phạm vi không?']),
            $this->guidedDay(5, 'video', 'common', 'Đọc Model Tree và đếm ModelItem', 'Model Tree', 60,
                'Học viên đọc cây mô hình, ModelItem, category và số lượng mà không thay đổi NWF/NWD.',
                ['Duyệt Model Tree.', 'Đếm nhóm phần tử.', 'Đối chiếu Selection Tree.'],
                ['Plugin ngày 4 chạy.', 'Model có nhiều discipline.'],
                ['Dùng ModelDataService/API đã chứng minh.', 'Chỉ đọc tree và lưu output riêng.', 'Đếm theo discipline/category.', 'Đối chiếu một nhánh với UI.', 'Ghi item thiếu property.'],
                ['Ảnh Tree/output.', 'Bảng số lượng.', 'Reflection traversal.'],
                ['Duyệt null child.', 'Đếm trùng instance.', 'Ghi đè output cũ.'],
                'Có báo cáo tree/model item kiểm chứng được',
                ['Root item ở đâu?', 'Đếm node hay geometry?', 'Output riêng thế nào?']),
            $this->guidedDay(6, 'video', 'common', 'Đọc Property và lập Data Profile', 'Properties', 60,
                'AI đọc Property category/item/source/value; học viên chuẩn hóa trường dữ liệu cho capstone.',
                ['Đọc property thật.', 'Có profile trường.', 'Xử lý null/missing.'],
                ['Hoàn thành traversal.', 'Có 5–10 item đối chiếu.'],
                ['Chọn item ở các discipline.', 'Xuất property rows riêng.', 'Điền DATA_PROFILE.md.', 'Đối chiếu Properties panel.', 'Ghi field bắt buộc/tùy chọn.'],
                ['DATA_PROFILE.md.', 'Bảng 5–10 item.', 'Ảnh Properties.'],
                ['Hard-code sai field.', 'Null làm crash.', 'Nhầm display/raw value.'],
                'Có profile đủ để xây rule/QA/report',
                ['Field key nào?', 'Property thiếu xử lý sao?', 'Giá trị đối chiếu ở đâu?']),
            $this->guidedDay(7, 'video', 'common', 'Chọn capstone và hoàn thiện Tool Brief', 'Chọn bài toán', 60,
                'Học viên chọn workflow Navisworks có output đo được và xác định capability cần test.',
                ['Chọn một nhánh.', 'Có input/output/acceptance.', 'Biết edition/capability bắt buộc.'],
                ['Hoàn thành ngày 1–6.', 'Có model mẫu và Data Profile.'],
                ['Chọn Search Set, Model QA, Clash/Coordination, Viewpoint hoặc Reporting.', 'Điền TOOL_BRIEF.md/DATA_PROFILE.md.', 'Yêu cầu AI phỏng vấn ngược.', 'Ghi Manage-only nếu có Clash.', 'Chuẩn bị review ngày 8.'],
                ['Tool Brief/Data Profile.', 'Sơ đồ input → rule → output.', 'Capability gate và ba test case.'],
                ['Chọn dashboard mọi thứ.', 'Không có nguồn data.', 'Tự nghĩ tolerance/Clash data.'],
                'Tool Brief đủ nhỏ và có dữ liệu thật',
                ['Output đối chiếu ở đâu?', 'Cần Manage hay Simulate?', 'Feature nào bỏ nếu thiếu evidence?']),
            $this->guidedDay(8, 'live', 'common', 'Review capability và chốt capstone', 'Livestream chốt đề tài', 120,
                'Mentor kiểm tra Tool Brief, Data Profile, edition và API spike trước khi xây logic.',
                ['Trình bày brief 3 phút.', 'Có go/no-go.', 'Có prompt triển khai.'],
                ['Đã nộp brief.', 'Có model và output mong muốn.'],
                ['Demo vấn đề → model → rule → output → giới hạn.', 'Ghi capability feedback.', 'Cập nhật brief/data profile.', 'Chờ mentor xác nhận.'],
                ['Video/bản ghi.', 'Brief sau review.', 'Biên bản capability gate.'],
                ['Không có source data.', 'Code trước duyệt.', 'Ghi runtime status sai.'],
                'Đề tài có capability và dữ liệu đủ làm MVP',
                ['Tính năng chính dùng service nào?', 'Model test nào?', 'Go/no-go nào?']),
            $this->guidedDay(9, 'video', 'search-set', 'Tạo Search Set và Selection Set', 'Search', 75,
                'Học viên xây rule tìm kiếm có cấu trúc từ Data Profile và kiểm tra số lượng/selection trong model.',
                ['Rule lặp lại được.', 'Xử lý empty/invalid.', 'Đối chiếu Selection Tree.'],
                ['Capstone duyệt.', 'Data Profile có key.'],
                ['Chọn category/property rule.', 'Validate field/operator/value.', 'Chạy rule và lưu result.', 'Đối chiếu selection.', 'Không ghi đè set cũ.'],
                ['Ảnh Search/Selection Set.', 'Rule JSON/markdown.', 'Bảng đối chiếu.'],
                ['Sai operator.', 'Property null crash.', 'Tạo set trùng tên.'],
                'Rule tìm kiếm trả đúng phần tử và báo empty rõ',
                ['Rule lấy field nào?', 'Empty báo gì?', 'Set lưu ở đâu?']),
            $this->guidedDay(10, 'video', 'common', 'Dựng DockPane và bộ lọc model', 'DockPane UI', 75,
                'AI tạo DockPane để nhập rule, xem result và chọn phần tử; UI phải gọi service thật.',
                ['DockPane mở/đóng.', 'Filter gọi service.', 'Có loading/empty/error.'],
                ['Có service hoặc spike ngày 9.', 'Có dữ liệu test.'],
                ['Đọc dockpane-ui skill.', 'Tách UI/service.', 'Build và mở DockPane.', 'Test query, empty, invalid, close và selection sync.'],
                ['Ảnh DockPane.', 'Video filter → selection.', 'Checklist UI states.'],
                ['Nút giả.', 'UI gọi API chưa kiểm chứng.', 'Query rỗng làm treo.'],
                'DockPane giúp kỹ sư lọc và kiểm tra model nhanh hơn',
                ['UI gọi service nào?', 'Empty hướng dẫn gì?', 'Selection sync kiểm chứng ra sao?']),
            $this->guidedDay(11, 'video', 'capstone', 'Thực hiện API spike cho Clash hoặc workflow đọc', 'API spike', 75,
                'Học viên kiểm chứng API lõi; Clash chỉ chạy trên Manage và dữ liệu có thật.',
                ['Có spike chạy hoặc kết luận capability không đủ.', 'Không tạo nút giả.', 'Ghi runtime evidence.'],
                ['Ngày 8 chốt nhánh.', 'Có Clash data hợp lệ nếu chọn Clash.'],
                ['Tạo spike nhỏ trước MVP.', 'Nếu Clash, xác nhận Manage và đọc clash thật.', 'Nếu thiếu data, chuyển sang read-only workflow.', 'Lưu result và cập nhật capability cá nhân.'],
                ['Video spike.', 'Log/result có nguồn.', 'Quyết định scope.'],
                ['Chạy Clash trên Simulate.', 'Dùng data giả.', 'Tuyên bố API support khi chưa test.'],
                'Biết API nào dùng được trước khi đầu tư MVP',
                ['Spike chứng minh gì?', 'Data đến từ đâu?', 'Khi nào đổi scope?']),
            $this->guidedDay(12, 'video', 'capstone', 'Hoàn thiện logic theo nhánh Navisworks', 'Capstone MVP', 90,
                'Xây logic Search Set, Model QA, Clash/Coordination, Viewpoint hoặc Reporting theo brief.',
                ['MVP end-to-end.', 'Output có nguồn/số liệu.', 'Xử lý missing/empty.'],
                ['API spike đạt.', 'Có acceptance test.'],
                ['Viết happy path và ba edge case.', 'Giữ capability boundary.', 'Chạy model thật và lưu output riêng.', 'Đối chiếu UI/report thủ công.', 'Cập nhật giới hạn.'],
                ['Video end-to-end.', 'Bảng test case.', 'Output có timestamp/source.'],
                ['Report không nguồn.', 'Empty result báo pass.', 'Clash sai edition.'],
                'MVP tạo output thực tế và giải thích được nguồn',
                ['Output đối chiếu thế nào?', 'Missing property xử lý sao?', 'Capability nào chưa làm?']),
            $this->guidedDay(13, 'video', 'reporting', 'Xuất báo cáo có nguồn dữ liệu', 'Reporting', 75,
                'AI tạo HTML/CSV/Excel tùy capability; học viên kiểm tra header, source, timestamp và không ghi đè report cũ.',
                ['Report mở được.', 'Dòng có định danh/source.', 'Có empty/error summary.'],
                ['MVP có output.', 'Có thư mục output riêng.'],
                ['Chọn format kit hỗ trợ.', 'Tạo report schema trước code.', 'Xuất normal và empty.', 'Đối chiếu 5 dòng với Navisworks.', 'Thêm timestamp/version phù hợp.'],
                ['File report.', 'Ảnh đối chiếu 5 dòng.', 'Report schema.'],
                ['Ghi đè report cũ.', 'Thiếu source.', 'CSV encoding lỗi.'],
                'Báo cáo có thể gửi và truy ngược về model',
                ['Dòng report lấy từ đâu?', 'Empty hiển thị sao?', 'File cũ bảo vệ thế nào?']),
            $this->guidedDay(14, 'video', 'viewpoint', 'Viewpoint, selection sync và section box', 'Coordination UI', 75,
                'Kết nối output với viewpoint/selection/section box khi capability đã được chứng minh.',
                ['Chọn đúng phần tử.', 'Viewpoint hoặc fallback rõ.', 'Không sửa model ngoài scope.'],
                ['MVP có result.', 'Capability viewpoint qua gate.'],
                ['Kiểm tra API trước code.', 'Test một/nhiều/stale item.', 'Lưu viewpoint riêng nếu cần.', 'Test section box trên bản sao.', 'Ghi fallback theo version.'],
                ['Video result → selection/viewpoint.', 'Ảnh section box nếu có.', 'Bảng version/capability.'],
                ['API chưa test.', 'Stale item exception.', 'Sửa NWD/NWF gốc.'],
                'Người dùng chuyển từ report tới vị trí cần kiểm tra',
                ['Stale item xử lý sao?', 'Version nào fallback?', 'Có thao tác ghi không?']),
            $this->guidedDay(15, 'live', 'common', 'Review MVP Navisworks với mentor', 'Livestream review MVP', 120,
                'Mentor kiểm tra plugin, DockPane, logic chính, output và capability boundary trước packaging.',
                ['Demo MVP 3 phút.', 'Có test input lỗi.', 'Có go/no-go.'],
                ['Ngày 14 có output/bug log.', 'Có model và build Release.'],
                ['Demo plugin → query → output → select/report.', 'Nếu Clash, chứng minh Manage runtime.', 'Ghi feedback critical/important.', 'Cập nhật capability matrix.', 'Sửa lỗi quan trọng trước ngày 16.'],
                ['Video demo.', 'Biên bản review.', 'MVP chạy thật.'],
                ['Demo ảnh cũ.', 'Nút capability chưa evidence.', 'Không empty/error test.'],
                'MVP chạy thật và được phép hoàn thiện/đóng gói',
                ['Output có source chưa?', 'Runtime status nào?', 'Critical bug nào?']),
            $this->guidedDay(16, 'video', 'capstone', 'Thêm logic nâng cao có giá trị thực tế', 'Nâng cao', 90,
                'Thêm đúng một nâng cấp: clash matrix/tolerance nhập vào, batch QA, nhiều rule, viewpoint folder hoặc report summary.',
                ['Gắn với brief.', 'Tolerance do người dùng cung cấp.', 'Có test boundary.'],
                ['MVP go ngày 15.', 'Có acceptance test.'],
                ['Viết test trước.', 'Cập nhật plan, không mở rộng lan.', 'Chạy normal/empty/boundary.', 'Đối chiếu output/log.', 'Cập nhật manual sơ bộ.'],
                ['Video nâng cấp.', 'Bảng boundary test.', 'Output/report cuối.'],
                ['Tự đặt tolerance.', 'Data giả.', 'Nâng cấp ngoài brief.'],
                'Tính năng nâng cao giải quyết một nhu cầu coordination cụ thể',
                ['Tolerance do ai cung cấp?', 'Boundary nào?', 'Output tái lập được không?']),
            $this->guidedDay(17, 'video', 'common', 'Đặt giới hạn an toàn và checkpoint', 'Safety', 60,
                'Tool bảo vệ model/report, có checkpoint và log; thao tác ghi cần xác nhận rõ.',
                ['Không ghi đè.', 'Có backup/checkpoint.', 'Log không lộ dữ liệu mật.'],
                ['Logic nâng cao chạy.', 'Có output riêng.'],
                ['Audit mọi thao tác ghi.', 'Thêm confirmation và output versioning.', 'Test cancel/error/rollback.', 'Kiểm tra thư mục output và log.', 'Ghi giới hạn Manage/Simulate/version.'],
                ['Safety checklist.', 'Video rollback/cancel.', 'Ảnh cảnh báo/output version.'],
                ['Ghi thẳng NWD/NWF.', 'Log chứa path nhạy cảm.', 'Không checkpoint.'],
                'Tool an toàn để dùng trên model/report thật',
                ['Thao tác nào cần confirmation?', 'Output cũ bảo vệ sao?', 'Log có dữ liệu nhạy cảm không?']),
            $this->guidedDay(18, 'video', 'common', 'Build profile và runtime test Navisworks', 'Multi-version', 75,
                'AI tạo artifact 2020–2026; học viên ghi Manage 2024 reference và tách build-only/runtime-tested.',
                ['Build đúng profile.', 'Ghi certified reference đúng.', 'Không overclaim.'],
                ['MVP review đạt.', 'Có version mục tiêu.'],
                ['Đọc navisworks-versions.json.', 'Build target và reference.', 'Test trực tiếp nếu có môi trường.', 'Ghi VERSION_SUPPORT.md.', 'Không dùng Clash trên Simulate.'],
                ['Build log.', 'Support matrix.', 'Video test hoặc ghi chưa test.'],
                ['Gọi version khác certified.', 'Dependency sai.', 'Test model mật.'],
                'Có compatibility claim trung thực và artifact đúng profile',
                ['Manage 2024 test sao?', 'Version nào build-only?', 'Feature nào bị khóa ở Simulate?']),
            $this->guidedDay(19, 'video', 'common', 'Đóng gói, cài đặt và rollback', 'Packaging', 75,
                'Gom DLL, manifest, dependency, icon, README và rollback thành bundle cài lại được.',
                ['Bundle sạch.', 'Cài lại được.', 'Rollback đúng phạm vi.'],
                ['Ngày 15 go.', 'Ngày 18 có artifact.', 'Navisworks sẽ đóng trước cài/gỡ.'],
                ['Lập manifest artifact.', 'Build Release và tạo dist.', 'Cài theo script sau xác nhận.', 'Mở Navisworks kiểm tra Ribbon/DockPane.', 'Gỡ/rollback và ghi hash.'],
                ['ZIP/bundle.', 'Video cài/gỡ.', 'Danh sách dependency/version.'],
                ['Cài khi app mở.', 'Manifest sai.', 'Thiếu runtime dependency.'],
                'Người khác có thể cài lại plugin từ bộ cài',
                ['Cài môi trường nào?', 'Rollback file nào?', 'Khi nào phải đóng Navisworks?']),
            $this->guidedDay(20, 'video', 'common', 'UAT trên model mẫu', 'UAT', 90,
                'Kiểm thử bình thường, thiếu Property, empty result và lỗi người dùng; Clash phải test trên Manage.',
                ['Có bảng pass/fail.', 'Output đối chiếu được.', 'Có regression.'],
                ['Có bundle ngày 19.', 'Có model mẫu không mật.'],
                ['Viết UAT trước.', 'Cài từ dist.', 'Chạy normal, empty, missing property, invalid rule và Clash nếu phù hợp.', 'Lưu video/output/log.', 'Sửa critical rồi chạy lại.'],
                ['Video A–Z 2–3 phút.', 'Bảng test.', 'Output và regression result.'],
                ['Chỉ test normal.', 'Không ghi source.', 'Dùng video cũ.'],
                'Tool hoạt động ở ba tình huống và có giới hạn rõ',
                ['Case bắt buộc pass?', 'Thiếu property báo sao?', 'Đối chiếu với UI nào?']),
            $this->guidedDay(21, 'live', 'common', 'Showcase tool Navisworks và bàn giao', 'Grand Finale', 120,
                'Trình bày bài toán coordination, quy trình AI, demo tool thật, report, bộ cài và support matrix.',
                ['Demo chạy thật.', 'Có dist/report/manual/brief cuối.', 'Nêu runtime limit.'],
                ['UAT đạt.', 'Có video dự phòng.'],
                ['Trình bày 3 phút bài toán, 3 phút demo, 2 phút Q&A, 1 phút feedback.', 'Mở model sạch, cài từ dist và chạy workflow.', 'Demo empty/error case.', 'Nộp Tool Brief, report, manual, video và VERSION_SUPPORT.md.'],
                ['Video/showcase trực tiếp.', 'Dist/report/manual.', 'Bài tổng kết before/after và capability limit.'],
                ['Demo ảnh.', 'Bộ cài không cài lại.', 'Tuyên bố runtime support không evidence.'],
                'Một tool Navisworks có thể demo, cài lại, xuất report và giải thích giới hạn',
                ['Bài toán coordination?', 'Nguồn dữ liệu?', 'Bước tiếp theo?']),
        ];
    }
}
