<?php

return [
    'membership_labels' => [
        'default' => 'Premium',
        'dscons' => 'Kỹ sư VIP',
    ],
    'quiz' => [
        'default' => ['show_agent_helper' => true],
        'dscons' => ['show_agent_helper' => false],
    ],
    'pillars' => [
        'default' => [
            'offer' => ['name' => 'Offer', 'icon' => 'layers', 'color' => '#D97706'],
            'traffic' => ['name' => 'Thu hút', 'icon' => 'bolt', 'color' => '#147F96'],
            'conversion' => ['name' => 'Chuyển đổi', 'icon' => 'target', 'color' => '#18794E'],
            'delivery' => ['name' => 'Cung ứng', 'icon' => 'settings', 'color' => '#2563EB'],
            'continuity' => ['name' => 'Continuity', 'icon' => 'users', 'color' => '#B42318'],
        ],
        'dscons' => [
            'offer' => ['name' => 'BIM & điều phối', 'icon' => 'layers', 'color' => '#125A96'],
            'traffic' => ['name' => 'Thiết kế MEP', 'icon' => 'compass', 'color' => '#147F96'],
            'conversion' => ['name' => 'Tự động hóa & dữ liệu', 'icon' => 'bolt', 'color' => '#1F77BE'],
            'delivery' => ['name' => 'Triển khai dự án', 'icon' => 'target', 'color' => '#2563EB'],
            'continuity' => ['name' => 'Tiêu chuẩn & vận hành', 'icon' => 'users', 'color' => '#0E7490'],
        ],
    ],
    'stages' => [
        'default' => [
            10 => 'Tân binh',
            30 => 'Freelancer',
            60 => 'Growing',
            100 => 'Chuyên gia',
            200 => 'Business Owner',
            'default' => 'Empire Builder',
        ],
        'dscons' => [
            10 => 'Người mới vào nghề',
            30 => 'Kỹ sư thực hành',
            60 => 'Kỹ sư nòng cốt',
            100 => 'Chuyên gia BIM/MEP',
            200 => 'Mentor DSCons',
            'default' => 'Mentor DSCons',
        ],
    ],
    'classes' => [
        'default' => [
            'offer_architect' => [
                'icon' => 'layers',
                'name' => 'Offer Architect',
                'pillar' => 'Offer',
                'description' => 'Thiết kế sản phẩm, định giá và value proposition.',
                'bonus' => '+20% XP khi review offer',
                'color' => '#D97706',
                'bg' => '#FFF7E6',
                'border' => '#F4C98B',
            ],
            'traffic_mage' => [
                'icon' => 'bolt',
                'name' => 'Traffic Mage',
                'pillar' => 'Thu hút',
                'description' => 'Content marketing, SEO, paid ads và viral growth.',
                'bonus' => 'Bài viết được ưu tiên +20% reach',
                'color' => '#147F96',
                'bg' => '#E6F6F8',
                'border' => '#A7D8E0',
            ],
            'conversion_ranger' => [
                'icon' => 'target',
                'name' => 'Conversion Ranger',
                'pillar' => 'Chuyển đổi',
                'description' => 'Copywriting, landing page, funnel và A/B test.',
                'bonus' => 'Review 5 sao được cộng thêm XP',
                'color' => '#18794E',
                'bg' => '#E9F8EF',
                'border' => '#A9DDBE',
            ],
            'delivery_assassin' => [
                'icon' => 'settings',
                'name' => 'Delivery Assassin',
                'pillar' => 'Cung ứng',
                'description' => 'Vận hành, tự động hóa, hệ thống và fulfilment.',
                'bonus' => 'Challenge đúng hạn được cộng thêm XP',
                'color' => '#2563EB',
                'bg' => '#EDF4FF',
                'border' => '#B7D0FA',
            ],
            'continuity_captain' => [
                'icon' => 'users',
                'name' => 'Continuity Captain',
                'pillar' => 'Continuity',
                'description' => 'Retention, affiliate, cộng đồng và LTV.',
                'bonus' => 'Thưởng khi phát triển cộng đồng',
                'color' => '#B42318',
                'bg' => '#FFF0EF',
                'border' => '#F0B9B4',
            ],
        ],
        'dscons' => [
            'offer_architect' => [
                'icon' => 'layers',
                'name' => 'BIM Coordinator',
                'pillar' => 'BIM & điều phối',
                'description' => 'Tổ chức mô hình, tiêu chuẩn và phối hợp các bộ môn.',
                'bonus' => 'Cộng XP khi chia sẻ workflow phối hợp',
                'color' => '#125A96',
                'bg' => '#E6F3FA',
                'border' => '#A9D2E8',
            ],
            'traffic_mage' => [
                'icon' => 'compass',
                'name' => 'MEP Design Engineer',
                'pillar' => 'Thiết kế MEP',
                'description' => 'Phát triển giải pháp thiết kế điện, nước và HVAC thực tế.',
                'bonus' => 'Cộng XP khi giải đáp vấn đề kỹ thuật',
                'color' => '#147F96',
                'bg' => '#E6F6F8',
                'border' => '#A7D8E0',
            ],
            'conversion_ranger' => [
                'icon' => 'bolt',
                'name' => 'BIM Automation Specialist',
                'pillar' => 'Tự động hóa & dữ liệu',
                'description' => 'Kết nối dữ liệu, script và công cụ để giảm việc lặp lại.',
                'bonus' => 'Cộng XP khi chia sẻ công cụ hữu ích',
                'color' => '#1F77BE',
                'bg' => '#EAF4FB',
                'border' => '#B5D8ED',
            ],
            'delivery_assassin' => [
                'icon' => 'target',
                'name' => 'Project Delivery Lead',
                'pillar' => 'Triển khai dự án',
                'description' => 'Đưa hồ sơ và mô hình từ kế hoạch đến bàn giao đúng chuẩn.',
                'bonus' => 'Cộng XP khi hoàn thành challenge thực chiến',
                'color' => '#2563EB',
                'bg' => '#EDF4FF',
                'border' => '#B7D0FA',
            ],
            'continuity_captain' => [
                'icon' => 'users',
                'name' => 'Digital Construction Lead',
                'pillar' => 'Tiêu chuẩn & vận hành',
                'description' => 'Xây quy trình, tiêu chuẩn và năng lực dùng lại trong dự án.',
                'bonus' => 'Cộng XP khi xây tài nguyên cho cộng đồng',
                'color' => '#0E7490',
                'bg' => '#E8F8FA',
                'border' => '#A8DDE3',
            ],
        ],
    ],
];
