<div style="max-width:820px;margin:0 auto;padding:28px 22px 60px;">
    <div style="margin-bottom:22px;"><div style="font-size:12px;text-transform:uppercase;letter-spacing:.14em;font-weight:800;color:var(--green);">Creator application</div><h1 style="margin:6px 0;color:var(--text);font-size:30px;letter-spacing:-.03em;">Đề xuất một cộng đồng mới</h1><p style="margin:0;color:var(--text-muted);line-height:1.6;">Mỗi community được DSCons duyệt để đảm bảo chất lượng nội dung và trải nghiệm học viên.</p></div>
    <form wire:submit="submit" class="rp-card" style="padding:24px;display:grid;gap:18px;">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;">
            <label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Tên community<input wire:model.live="name" class="form-control" placeholder="Ví dụ: BIM Automation Lab">@error('name')<span class="field-error">{{ $message }}</span>@enderror</label>
            <label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Slug<input wire:model="slug" class="form-control" placeholder="bim-automation">@error('slug')<span class="field-error">{{ $message }}</span>@enderror</label>
        </div>
        <label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Tagline<input wire:model="tagline" class="form-control" placeholder="Một câu mô tả ngắn"></label>
        <label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Mô tả community<textarea wire:model="description" class="form-control" rows="4" placeholder="Community giúp thành viên đạt được điều gì?"></textarea>@error('description')<span class="field-error">{{ $message }}</span>@enderror</label>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;"><label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Chủ đề giảng dạy<input wire:model="teachingTopic" class="form-control" placeholder="BIM, quản trị dự án…">@error('teachingTopic')<span class="field-error">{{ $message }}</span>@enderror</label><label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Giá Premium dự kiến (VNĐ)<input wire:model="proposedPremiumPrice" type="number" min="0" class="form-control" placeholder="0"></label></div>
        <label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Mô tả chương trình dự kiến<textarea wire:model="programDescription" class="form-control" rows="4" placeholder="Khóa học, challenge hoặc lộ trình bạn muốn mở…"></textarea>@error('programDescription')<span class="field-error">{{ $message }}</span>@enderror</label>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;"><label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Tài khoản nhận thanh toán<input wire:model="proposedSepayAccount" class="form-control" placeholder="Tùy chọn"></label><label style="display:grid;gap:7px;font-size:13px;font-weight:700;color:var(--text);">Ngân hàng<input wire:model="proposedSepayBank" class="form-control" placeholder="Tùy chọn"></label></div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;"><label class="upload-tile">Logo<input wire:model="logo" type="file" accept="image/*">@if($logo)<span>{{ $logo->getClientOriginalName() }}</span>@endif</label><label class="upload-tile">Banner<input wire:model="banner" type="file" accept="image/*">@if($banner)<span>{{ $banner->getClientOriginalName() }}</span>@endif</label></div>
        <div style="display:flex;justify-content:flex-end;gap:10px;padding-top:4px;"><a href="{{ route('communities') }}" class="ds-btn" style="text-decoration:none;">Hủy</a><button wire:loading.attr="disabled" class="ds-btn ds-btn-primary" type="submit"><span wire:loading.remove>Gửi hồ sơ</span><span wire:loading>Đang gửi…</span></button></div>
    </form>
</div>
