<section class="cv-workspace">
    <style>
        .cv-workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(330px,440px);gap:1rem;align-items:start}.cv-form{display:grid;gap:1rem}.cv-form label{display:grid;gap:.35rem;color:#29485B;font-size:.8rem;font-weight:750}.cv-form input,.cv-form textarea,.cv-form select{width:100%;box-sizing:border-box}.cv-group{padding:1rem;border:1px solid #D7E5EA;border-radius:14px;background:#fff}.cv-group h2{display:flex;align-items:center;gap:.45rem;margin:0 0 .25rem;color:#123B59;font-size:.92rem}.cv-group-intro{margin:0 0 .8rem;color:#60798A;font-size:.73rem;line-height:1.5}.cv-preview{position:sticky;top:1rem;background:#fff;border:1px solid #D7E5EA;border-radius:16px;box-shadow:0 12px 30px rgba(18,59,89,.08)}.cv-sheet{min-height:700px;padding:1.45rem;color:#243746}.cv-sheet h2{margin:0;color:var(--cv-accent,#1F77BE);font-size:1.45rem}.cv-kicker{color:#61798A;font-size:.7rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900}.cv-section{margin-top:1.1rem}.cv-section h3{margin:0 0 .35rem;color:#173042;font-size:.72rem;text-transform:uppercase;letter-spacing:.1em;border-bottom:1px solid #D7E5EA;padding-bottom:.3rem}.cv-sheet p,.cv-sheet li{font-size:.77rem;line-height:1.55}.cv-sheet ul{padding-left:1.1rem;margin:.3rem 0}.cv-section-nav{display:flex;gap:.35rem;flex-wrap:wrap;margin:.7rem 0 1rem}.cv-section-nav a{padding:.38rem .55rem;border:1px solid #CFE3ED;border-radius:999px;color:#236684;text-decoration:none;font-size:.68rem;font-weight:800}.cv-section-nav a:hover{background:#EAF5FB;border-color:#1F77BE}.cv-admin-preview{display:flex;align-items:center;justify-content:space-between;gap:.75rem;margin:.7rem 0 1rem;padding:.75rem .85rem;border:1px solid #A8CDE1;border-radius:12px;background:#EAF6FB;color:#174D70;font-size:.78rem;line-height:1.45}.cv-admin-preview strong{display:block;font-size:.82rem}.cv-admin-preview a{color:#125A96;font-weight:800;text-decoration:none;white-space:nowrap}.cv-admin-preview a:hover{text-decoration:underline}.cv-form.is-admin-preview{pointer-events:none;user-select:none;opacity:.82}@media(max-width:900px){.cv-workspace{grid-template-columns:1fr}.cv-preview{position:static}.cv-preview-card{order:2}}@media(max-width:600px){.cv-form .cv-two-col{grid-template-columns:1fr!important}.cv-admin-preview{align-items:flex-start;flex-direction:column}}
    </style>

    <div>
        <div style="display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin-bottom:.45rem;">
            <div><div class="talent-kicker">{{ brand()->name }} · Hồ sơ nghề nghiệp</div><h1 class="talent-heading">{{ $isAdminPreview ? 'Xem trước CV ứng viên' : 'CV của tôi' }}</h1><p class="talent-subtitle" style="margin:.4rem 0 0;">{{ $isAdminPreview ? 'Kiểm tra đúng trải nghiệm ứng viên trước khi gửi cho người dùng.' : 'Hoàn thiện từng nhóm thông tin. Recruiter chỉ xem dữ liệu nghề nghiệp, còn thông tin liên hệ vẫn do bạn kiểm soát.' }}</p></div>
            <span class="talent-status" style="background:{{ $isPublished ? '#EDF8F1' : '#FFF7E9' }};color:{{ $isPublished ? '#18794E' : '#A36505' }};"><x-icon name="{{ $isPublished ? 'check-circle' : 'clock' }}" size="13" /> {{ $isPublished ? 'Đang công khai' : 'Bản nháp' }}</span>
        </div>
        <nav class="cv-section-nav" aria-label="Các phần CV"><a href="#cv-basic">Thông tin cơ bản</a><a href="#cv-skills">Kỹ năng</a><a href="#cv-experience">Kinh nghiệm</a><a href="#cv-projects">Dự án</a><a href="#cv-education">Học vấn & chứng chỉ</a><a href="#cv-privacy">Quyền riêng tư</a></nav>

        @if(!$isAdminPreview && $incomingRequests->isNotEmpty())
            <div class="talent-card" style="padding:1rem;margin-bottom:.9rem;border-color:#F4C98B;background:#FFF9EF;"><div style="display:flex;gap:.55rem;align-items:center;"><x-icon name="briefcase" size="17" color="#A36505" /><strong style="font-size:.85rem;">Yêu cầu tuyển dụng mới</strong></div>@foreach($incomingRequests as $request)<div style="display:flex;align-items:center;justify-content:space-between;gap:.7rem;flex-wrap:wrap;padding:.7rem 0;border-bottom:1px solid #F4E5C9;"><span style="font-size:.8rem;">{{ $request->recruiter->recruiterProfile?->company_name ?? 'Nhà tuyển dụng đã xác minh' }}<small style="display:block;color:#8B6B35;margin-top:.15rem;">{{ $request->message ?: 'Muốn trao đổi về cơ hội phù hợp với hồ sơ của bạn.' }}</small></span><span style="display:flex;gap:.4rem;"><button type="button" wire:click="acceptRequest({{ $request->id }})" class="talent-btn talent-btn-primary" title="Chấp thuận yêu cầu liên hệ" aria-label="Chấp thuận yêu cầu liên hệ" style="min-height:33px;padding:.4rem .6rem;font-size:.7rem;">Chấp thuận</button><button type="button" wire:click="rejectRequest({{ $request->id }})" class="talent-btn talent-btn-secondary" title="Từ chối yêu cầu liên hệ" aria-label="Từ chối yêu cầu liên hệ" style="min-height:33px;padding:.4rem .6rem;font-size:.7rem;">Từ chối</button></span></div>@endforeach</div>
        @endif

        @if($isAdminPreview)
            <div class="cv-admin-preview" role="status"><div><strong>Chế độ xem trước của admin</strong>Đây là giao diện của ứng viên. Các trường và nút lưu đã được khóa, dữ liệu gốc không thể bị thay đổi ở đây.</div><a href="{{ community_route('manage.recruitment') }}">Quay lại quản lý Talent</a></div>
        @endif
        <form wire:submit="save" class="cv-form {{ $isAdminPreview ? 'is-admin-preview' : '' }}" @if($isAdminPreview) inert aria-disabled="true" @endif>
            <div id="cv-basic" class="cv-group">
                <h2><x-icon name="user" size="17" /> Thông tin cơ bản</h2><p class="cv-group-intro">Thông tin giúp recruiter hiểu nhanh bạn đang làm gì và phù hợp với loại dự án nào.</p>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem;" class="cv-two-col"><label>Tiêu đề chuyên môn<input wire:model="headline" class="talent-input" placeholder="BIM Coordinator / MEP Design Engineer">@error('headline')<small style="color:#B42318;">{{ $message }}</small>@enderror</label><label>Chuyên môn<select wire:model="discipline" class="talent-input"><option>BIM</option><option>MEP</option><option>HVAC</option><option>Electrical</option><option>Plumbing</option></select></label></div>
                <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem;margin-top:.7rem;" class="cv-two-col"><label>Số năm<input wire:model="yearsExperience" type="number" min="0" class="talent-input"></label><label>Địa điểm<input wire:model="location" class="talent-input" placeholder="Hà Nội"></label><label>Work mode<select wire:model="workMode" class="talent-input"><option>Hybrid</option><option>On-site</option><option>Remote</option></select></label><label>Availability<select wire:model="availability" class="talent-input"><option>Đang cập nhật</option><option>Sẵn sàng</option><option>Trong 1-3 tháng</option></select></label></div>
                <label style="margin-top:.7rem;">Tóm tắt nghề nghiệp<textarea wire:model="summary" class="talent-input" rows="4" placeholder="Bạn mạnh ở loại dự án nào? Đã tạo ra kết quả gì?"></textarea></label>
            </div>

            <div id="cv-skills" class="cv-group"><h2><x-icon name="target" size="17" /> Kỹ năng & công cụ</h2><p class="cv-group-intro">Nhập cách nhau bằng dấu phẩy. Đây là dữ liệu recruiter dùng để lọc ứng viên.</p><label>Kỹ năng chính<input wire:model="skillsText" class="talent-input" placeholder="Revit, Navisworks, Dynamo, HVAC, Clash Detection">@error('skillsText')<small style="color:#B42318;">{{ $message }}</small>@enderror</label><label style="margin-top:.7rem;">Ngôn ngữ / mức độ<textarea wire:model="languagesText" class="talent-input" rows="2" placeholder="English · Intermediate, Vietnamese · Native"></textarea></label></div>

            <div id="cv-experience" class="cv-group"><h2><x-icon name="briefcase" size="17" /> Kinh nghiệm làm việc</h2><p class="cv-group-intro">Mỗi dòng là một kinh nghiệm hoặc vai trò. Có thể ghi công cụ, loại dự án và kết quả.</p><label>Kinh nghiệm<textarea wire:model="experiencesText" class="talent-input" rows="5" placeholder="BIM Coordinator · Dự án văn phòng · Revit/Navisworks · Điều phối clash"></textarea></label></div>

            <div id="cv-projects" class="cv-group"><h2><x-icon name="layers" size="17" /> Dự án tiêu biểu</h2><p class="cv-group-intro">Chọn 2-4 dự án thể hiện rõ năng lực thực tế. Không đưa dữ liệu mật của công ty.</p><label>Dự án / vai trò<textarea wire:model="projectsText" class="talent-input" rows="4" placeholder="Bệnh viện ABC · BIM Modeler · MEPF coordination · 120.000 m²"></textarea></label></div>

            <div id="cv-education" class="cv-group"><h2><x-icon name="graduation" size="17" /> Học vấn & chứng chỉ</h2><p class="cv-group-intro">Ghi trường, chuyên ngành, chứng chỉ Revit/Navisworks hoặc chứng nhận nghề nghiệp.</p><label>Học vấn<textarea wire:model="educationText" class="talent-input" rows="3" placeholder="Đại học X · Kỹ thuật cơ điện"></textarea></label><label style="margin-top:.7rem;">Chứng chỉ<textarea wire:model="certificationsText" class="talent-input" rows="3" placeholder="Autodesk Certified Professional · Revit MEP · 2025"></textarea></label></div>

            <div class="cv-group"><h2><x-icon name="palette" size="17" /> Giao diện CV</h2><p class="cv-group-intro">Chọn mẫu và màu để tạo CV dễ đọc khi recruiter mở hồ sơ.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem;" class="cv-two-col"><label>Mẫu CV<select wire:model="template" class="talent-input"><option value="technical-clean">Technical Clean · Kỹ thuật rõ ràng</option><option value="bim-portfolio">BIM Portfolio · Nổi bật dự án</option><option value="mep-compact">MEP Compact · Gọn cho recruiter</option></select></label><label>Màu chủ đạo<input wire:model="accentColor" type="color" class="talent-input" style="height:42px;padding:.2rem;"></label></div></div>

            <div id="cv-privacy" class="cv-group"><h2><x-icon name="lock" size="17" /> Quyền riêng tư & liên hệ</h2><p class="cv-group-intro">Các thông tin dưới đây chỉ được mở sau khi bạn chấp thuận một yêu cầu tuyển dụng.</p><label>Email tài khoản<input value="{{ $profileEmail }}" class="talent-input" readonly aria-label="Email tài khoản, chỉ đọc"></label><label style="margin-top:.7rem;">Số điện thoại<input wire:model="contactPhone" class="talent-input" placeholder="Số điện thoại chỉ lộ theo cài đặt"></label><div style="display:grid;gap:.45rem;margin-top:.7rem;"><label style="display:flex;gap:.4rem;align-items:center;font-weight:600;font-size:.75rem;"><input wire:model="showEmail" type="checkbox" style="width:auto;"> Cho phép lộ email sau khi tôi chấp thuận</label><label style="display:flex;gap:.4rem;align-items:center;font-weight:600;font-size:.75rem;"><input wire:model="showPhone" type="checkbox" style="width:auto;"> Cho phép lộ số điện thoại sau khi tôi chấp thuận</label></div></div>

            <div style="display:flex;justify-content:flex-end;gap:.55rem;flex-wrap:wrap;"><button type="button" wire:click="save(false)" class="talent-btn talent-btn-secondary" title="Lưu CV nhưng chưa cho recruiter tìm kiếm" aria-label="Lưu CV bản nháp"><x-icon name="archive" size="15" /> Lưu bản nháp</button><button type="button" wire:click="save(true)" class="talent-btn talent-btn-primary" title="Lưu CV và cho recruiter tìm kiếm" aria-label="Lưu và công khai CV"><x-icon name="check" size="15" /> Lưu & công khai CV</button></div>
        </form>
    </div>

    <aside class="cv-preview-card cv-preview" aria-label="Bản xem trước CV"><div class="cv-sheet" style="--cv-accent:{{ $accentColor }};"><span class="cv-kicker">{{ brand()->name }} Talent · {{ $discipline }}</span><h2>{{ $headline ?: 'Tiêu đề chuyên môn' }}</h2><p style="margin:.25rem 0;color:#61798A;">{{ $yearsExperience }} năm · {{ $location ?: 'Địa điểm' }} · {{ $workMode }} · {{ $availability }}</p><div class="cv-section"><h3>Tóm tắt</h3><p>{{ $summary ?: 'Tóm tắt kinh nghiệm và thế mạnh của bạn sẽ hiển thị ở đây.' }}</p></div><div class="cv-section"><h3>Kỹ năng</h3><ul>@forelse(array_filter(array_map('trim', preg_split('/[,\n]+/', $skillsText))) as $skill)<li>{{ $skill }}</li>@empty<li>Chưa thêm kỹ năng</li>@endforelse</ul></div><div class="cv-section"><h3>Kinh nghiệm</h3><ul>@forelse(array_filter(array_map('trim', preg_split('/\r?\n/', $experiencesText))) as $experience)<li>{{ $experience }}</li>@empty<li>Chưa thêm kinh nghiệm</li>@endforelse</ul></div><div class="cv-section"><h3>Dự án tiêu biểu</h3><ul>@forelse(array_filter(array_map('trim', preg_split('/\r?\n/', $projectsText))) as $project)<li>{{ $project }}</li>@empty<li>Chưa thêm dự án</li>@endforelse</ul></div><div class="cv-section"><h3>Học vấn & chứng chỉ</h3><p>{{ $educationText ?: 'Chưa thêm học vấn' }}</p><p>{{ $certificationsText ?: 'Chưa thêm chứng chỉ' }}</p></div></div></aside>
</section>
