<section class="talent-request-page" style="max-width:900px;margin:0 auto;">
    <div style="display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin-bottom:1rem;"><div><div class="talent-kicker">{{ brand()->name }} · Hồ sơ nghề nghiệp</div><h1 class="talent-heading">Yêu cầu tuyển dụng</h1><p class="talent-subtitle" style="margin:.4rem 0 0;">Quản lý ai được phép mở liên hệ với bạn. Bạn luôn là người quyết định kết nối.</p></div><a href="{{ community_route('engineer.cv') }}" class="talent-btn talent-btn-primary"><x-icon name="cv" size="15" /> Chỉnh CV của tôi</a></div>
    <div class="talent-card" style="padding:1rem;margin-bottom:.9rem;background:#F5FAFC;"><div style="display:flex;gap:.55rem;align-items:flex-start;"><x-icon name="lock" size="18" color="#1F77BE" /><div><strong style="font-size:.82rem;">Thông tin luôn được ẩn trước khi bạn đồng ý</strong><p style="font-size:.75rem;line-height:1.55;color:#60798A;margin:.25rem 0 0;">Nhà tuyển dụng chỉ thấy năng lực, kinh nghiệm và CV ẩn danh. Email, số điện thoại và thông tin cá nhân chỉ mở sau khi bạn chấp thuận.</p></div></div></div>
    <div style="display:grid;gap:.7rem;">
        @forelse($requests as $request)
            @php($profile = $request->recruiter->recruiterProfile)
            <article class="talent-card" style="padding:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap;"><div><span style="display:block;color:#60798A;font-size:.68rem;font-weight:850;letter-spacing:.08em;text-transform:uppercase;">{{ $request->status === 'accepted' ? 'Đã kết nối' : ($request->status === 'pending' ? 'Cần phản hồi' : 'Đã xử lý') }}</span><h2 style="font-size:.95rem;margin:.28rem 0;">{{ $profile?->company_name ?? 'Nhà tuyển dụng đã xác minh' }}</h2><p style="font-size:.76rem;color:#60798A;margin:0;">{{ $request->message ?: 'Nhà tuyển dụng muốn trao đổi về một cơ hội phù hợp với CV của bạn.' }}</p><small style="display:block;color:#8AA0AC;margin-top:.35rem;">{{ $request->created_at?->diffForHumans() }}</small></div><div style="display:flex;align-items:center;gap:.45rem;flex-wrap:wrap;">@if($request->status === 'pending')<button wire:click="acceptRequest({{ $request->id }})" class="talent-btn talent-btn-primary" style="min-height:36px;padding:.45rem .65rem;font-size:.72rem;">Chấp thuận</button><button wire:click="rejectRequest({{ $request->id }})" class="talent-btn talent-btn-secondary" style="min-height:36px;padding:.45rem .65rem;font-size:.72rem;">Từ chối</button>@elseif($request->status === 'accepted')<span class="talent-status"><x-icon name="check-circle" size="13" /> Đã mở liên hệ</span>@if($request->conversation)<a href="{{ community_route('messages', ['conversation' => $request->conversation->id]) }}" class="talent-btn talent-btn-secondary" style="min-height:36px;padding:.45rem .65rem;font-size:.72rem;">Mở tin nhắn</a>@endif@elseif($request->status === 'rejected')<span class="talent-status" style="background:#FFF1F0;color:#B42318;">Đã từ chối</span>@else<span class="talent-status" style="background:#FFF7E9;color:#A36505;">Hết hạn</span>@endif</div></article>
        @empty
            <div class="talent-card" style="padding:2.5rem;text-align:center;"><span style="width:46px;height:46px;margin:auto;display:grid;place-items:center;border-radius:13px;background:#EAF5FB;color:#1F77BE;"><x-icon name="briefcase" size="21" /></span><h2 style="font-size:1rem;margin:.75rem 0 .35rem;">Chưa có yêu cầu tuyển dụng</h2><p style="font-size:.78rem;color:#60798A;margin:0;">Khi một recruiter quan tâm đến CV của bạn, yêu cầu sẽ xuất hiện ở đây.</p></div>
        @endforelse
    </div>
</section>
